# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

user_a = User.create(name: "Donnovan")
user_b = User.create(name: "Phil")

snake_a  = Snake.create(body: "[{x: 13, y: 19}, {x: 12, y: 19}, {x: 11, y: 19}]")
snake_b = Snake.create(body: ["{x: 19, y: 2}, {x: 19, y: 3}, {x: 19, y: 4}"])
snake_c  = Snake.create(body: "[{x: 13, y: 19}, {x: 12, y: 19}, {x: 11, y: 19}]")
snake_d = Snake.create(body: ["{x: 19, y: 2}, {x: 19, y: 3}, {x: 19, y: 4}"])
snake_e  = Snake.create(body: "[{x: 13, y: 19}, {x: 12, y: 19}, {x: 11, y: 19}]")
snake_f = Snake.create(body: ["{x: 19, y: 2}, {x: 19, y: 3}, {x: 19, y: 4}"])
snake_g  = Snake.create(body: "[{x: 13, y: 19}, {x: 12, y: 19}, {x: 11, y: 19}]")
snake_h = Snake.create(body: ["{x: 19, y: 2}, {x: 19, y: 3}, {x: 19, y: 4}"])
snake_i  = Snake.create(body: "[{x: 13, y: 19}, {x: 12, y: 19}, {x: 11, y: 19}]")
snake_j = Snake.create(body: ["{x: 19, y: 2}, {x: 19, y: 3}, {x: 19, y: 4}"])
snake_k  = Snake.create(body: "[{x: 13, y: 19}, {x: 12, y: 19}, {x: 11, y: 19}]")

skull = Consumable.create(position: "{x: 16 , y: 14}")
apple= Consumable.create(position: "{x: 13 , y: 3}")
skull1 = Consumable.create(position: "{x: 16 , y: 14}")
apple1= Consumable.create(position: "{x: 13 , y: 3}")
skull2 = Consumable.create(position: "{x: 16 , y: 14}")
apple2= Consumable.create(position: "{x: 13 , y: 3}")
skull3 = Consumable.create(position: "{x: 16 , y: 14}")
apple3 = Consumable.create(position: "{x: 13 , y: 3}")
skull4 = Consumable.create(position: "{x: 16 , y: 14}")
apple4= Consumable.create(position: "{x: 13 , y: 3}")
skull5 = Consumable.create(position: "{x: 16 , y: 14}")
apple5= Consumable.create(position: "{x: 13 , y: 3}")
skull6 = Consumable.create(position: "{x: 16 , y: 14}")
apple6= Consumable.create(position: "{x: 13 , y: 3}")
skull7 = Consumable.create(position: "{x: 16 , y: 14}")
apple7 = Consumable.create(position: "{x: 13 , y: 3}")
skull8 = Consumable.create(position: "{x: 16 , y: 14}")
apple8 = Consumable.create(position: "{x: 13 , y: 3}")
skull9 = Consumable.create(position: "{x: 16 , y: 14}")
apple9 = Consumable.create(position: "{x: 13 , y: 3}")
skull10 = Consumable.create(position: "{x: 16 , y: 14}")
apple10 = Consumable.create(position: "{x: 13 , y: 3}")

game_a = user_a.games.create(snake: snake_a, consumables: [skull, apple])
game1 = user_a.games.create(snake: snake_b, consumables: [skull1, apple1], score: 20)
game2 = user_a.games.create(snake: snake_c, consumables: [skull2, apple2], score: 30, completed: true)
game3 = user_a.games.create(snake: snake_d, consumables: [skull3, apple3], score: 40)
game4 = user_a.games.create(snake: snake_e, consumables: [skull4, apple4], score: 50, completed: true)
game5 = user_a.games.create(snake: snake_f, consumables: [skull5, apple5], score: 60)
game6 = user_b.games.create(snake: snake_g, consumables: [skull6, apple6], score: 70, completed: true)
game7 = user_b.games.create(snake: snake_h, consumables: [skull7, apple7], score: 80)
game8 = user_b.games.create(snake: snake_i, consumables: [skull8, apple8], score: 90, completed: true)
game9 = user_b.games.create(snake: snake_j, consumables: [skull9, apple9], score: 100)
game10 = user_b.games.create(snake: snake_k, consumables: [skull10, apple10], score: 120, completed: true)